# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Transportes-Juanva_development

  #username: jason

  #password: legolas2416

  #host: localhost

  #port: 5432

  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:

  #min_messages: notice

test:
  <<: *default
  database: Transportes-Juanva_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  adapter: postgresql
  database: Transportes-Juanva_production
  username: Transportes-Juanva
  password: <%= ENV['TRANSPORTES-JUANVA_DATABASE_PASSWORD'] %>
